version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=94fcc6d5-916c-4081-ba39-fddae907e23c
      - POSTGRES_USER=postgres
      - POSTGRES_DB=instagram-data
    ports:
      - 5432:5432
    volumes:
      - ./.tmp/data/postgres:/var/lib/postgresql/data
